"""Emit the two per-mode LaTeX tables Ch. 6 needs, from the downloaded histories.

  tab_performance_rect2net.tex  -> §6.2, control performance (reported direction)
  tab_reverse_transfer.tex      -> §6.6, both directions side by side

Generated rather than typed, so the manuscript cannot drift from the data.
Copy the outputs into phd/tables/ and \\input them.

Rows are ordered least-to-most spatial, matching tab:mdp:obs-modes in Ch. 5, so
a reader can carry one ordering through the manuscript.
"""

import os

import pandas as pd

BASE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(BASE, "out_q_calibration")

# least -> most spatial content; baselines first
ORDER = ["RAND", "POMDP", "S3m", "S3s", "S3sm", "S5m", "I1", "I1m", "I2", "I2m"]

# where the rule separating baselines from learned modes goes
RULE_AFTER = "POMDP"


def load(direction):
    df = pd.read_csv(os.path.join(OUT, f"summary_{direction}.csv")).set_index("id")
    return df.reindex([i for i in ORDER if i in df.index])


def esc(s):
    return s.replace("_", r"\_")


def num(x, sign=True):
    if pd.isna(x):
        return r"\multicolumn{1}{c}{--}"
    return f"${x:+.1f}$" if sign else f"${x:.1f}$"


def performance_table():
    # Identified by short ID only, as in the reverse-transfer table.  Spelling out
    # spatial_scalars_cells_spatial_no_scalars_substrates_m1m2 in a column
    # alongside five numeric ones overflows the text block, and Ch. 5's
    # tab:mdp:obs-modes already carries the ID-to-mode mapping.
    d = load("rect2net")
    rows = []
    for mid, r in d.iterrows():
        rows.append(
            f"  {mid} & {int(r['n'])} & "
            f"{num(r['train_return_mu'])} & {num(r['train_return_sd'], False)} & "
            f"{num(r['test_return_mu'])} & {num(r['test_return_sd'], False)} & "
            f"{num(r['gap'])} \\\\"
        )
        if mid == RULE_AFTER:
            rows.append(r"  \midrule")
    return r"""% GENERATED by figures_plotting/emit_ch6_tables.py -- do not hand-edit.
% train = rectangle, test = network-field.  n=5 seeds (first five by seed id);
% mean of the last 50 (train) / 20 (test) EWMA-50 smoothed points per seed.
\begin{tabular}{lcccccc}
  \toprule
  \textbf{ID} & \textbf{$n$}
  & \multicolumn{2}{c}{\textbf{Train (rectangle)}}
  & \multicolumn{2}{c}{\textbf{Test (network-field)}}
  & \textbf{Gap} \\
  \cmidrule(lr){3-4}\cmidrule(lr){5-6}
  & & $\mu$ & $\sigma$ & $\mu$ & $\sigma$ & \\
  \midrule
""" + "\n".join(rows) + r"""
  \bottomrule
\end{tabular}
"""


def reverse_table():
    f, b = load("rect2net"), load("net2rect")
    rows = []
    for mid in [i for i in ORDER if i in f.index and i in b.index]:
        rf, rb = f.loc[mid], b.loc[mid]
        rows.append(
            f"  {mid} & "
            f"{num(rf['train_return_mu'])} & {num(rf['test_return_mu'])} & "
            f"{num(rf['gap'])} & {num(rf['q_mae_mu'], False)} & "
            f"{num(rb['train_return_mu'])} & {num(rb['test_return_mu'])} & "
            f"{num(rb['gap'])} & {num(rb['q_mae_mu'], False)} \\\\"
        )
        if mid == RULE_AFTER:
            rows.append(r"  \midrule")
    return r"""% GENERATED by figures_plotting/emit_ch6_tables.py -- do not hand-edit.
% Both transfer directions, same protocol, n=5 seeds each.
% m is test_q_mae at end of training; the random baseline logs no Q metrics.
\begin{tabular}{lcccc@{\hskip 1.5em}cccc}
  \toprule
  & \multicolumn{4}{c}{\textbf{rectangle $\to$ network-field}}
  & \multicolumn{4}{c}{\textbf{network-field $\to$ rectangle}} \\
  \cmidrule(lr){2-5}\cmidrule(lr){6-9}
  \textbf{ID} & Train & Test & Gap & $m$ & Train & Test & Gap & $m$ \\
  \midrule
""" + "\n".join(rows) + r"""
  \bottomrule
\end{tabular}
"""


if __name__ == "__main__":
    for name, tex in [("tab_performance_rect2net", performance_table()),
                      ("tab_reverse_transfer", reverse_table())]:
        p = os.path.join(OUT, f"{name}.tex")
        with open(p, "w") as fh:
            fh.write(tex)
        print("wrote", p)
