#!/usr/bin/env python3
"""Emit tables/tab_aiming_net2rect.tex from stage3_alignment_reverse.csv (C6).

Mirrors the forward table emitted by emit_ch6_tables.py::aiming_table(), so the
two can be read side by side. Scalar block first, then image, as in the forward
table. Episode counts are train + test summed, matching the forward convention.
"""
import os
import pandas as pd

BASE = os.path.dirname(os.path.abspath(__file__))
ID = {"img_mc_cells": "I1", "img_mc_cells_m1m2": "I1m",
      "img_mc_cells_substrates": "I2", "img_mc_cells_substrates_m1m2": "I2m",
      "spatial_scalars_cells_substrates": "S3s", "spatial_scalars_cells_m1m2": "S3m",
      "spatial_scalars_cells_substrates_m1m2": "S3sm",
      "spatial_scalars_cells_spatial_no_scalars_substrates_m1m2": "S5m"}


def main():
    df = pd.read_csv(os.path.join(BASE, "stage3_alignment_reverse.csv"))
    df["id"] = df["mode"].map(ID)
    p = df.pivot_table(index=["family", "id"], columns="split",
                       values=["align_mean", "align_sd", "n_eps", "final_tumor_med"])
    L = ["% GENERATED by figures_plotting/emit_reverse_aiming_table.py -- do not hand-edit.",
         "% Source: stage3_alignment_reverse.csv (stage3_transfer_reverse.py).",
         "% train = network-field, test = rectangle (reverse direction).  Aim = mean",
         "% normalised distance from the injection centre to the tumour centroid over",
         "% dosed steps; lower is better.  Excludes new_chemotaxis and uniform-action runs.",
         r"\begin{tabular}{lccccccc}", r"  \toprule",
         r"  \textbf{ID} & \textbf{episodes}",
         r"  & \multicolumn{3}{c}{\textbf{Aiming error}}",
         r"  & \textbf{s.d. ratio}",
         r"  & \multicolumn{2}{c}{\textbf{Final tumour}} \\",
         r"  \cmidrule(lr){3-5}\cmidrule(lr){7-8}",
         r"  & & train & test & $\Delta$ & test/train & train & test \\", r"  \midrule"]
    for fam in ("scalar", "image"):
        for i in sorted([j for f, j in p.index if f == fam]):
            r = p.loc[(fam, i)]
            n = int(r[("n_eps", "train")] + r[("n_eps", "test")])
            at, ae = r[("align_mean", "train")], r[("align_mean", "test")]
            sr = r[("align_sd", "test")] / r[("align_sd", "train")]
            L.append(f"  {i} & {n} & ${at:.3f}$ & ${ae:.3f}$ & ${ae - at:+.3f}$ & "
                     f"${sr:.2f}\\times$ & ${int(r[('final_tumor_med','train')])}$ & "
                     f"${int(r[('final_tumor_med','test')])}$ \\\\")
        if fam == "scalar":
            L.append(r"  \midrule")
    L += [r"  \bottomrule", r"\end{tabular}"]
    out = os.path.join(BASE, "tab_aiming_net2rect.tex")
    with open(out, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {out}  ({int(df.n_eps.sum())} episodes)")


if __name__ == "__main__":
    main()
