"""Bootstrap version of the EWRL-2026 TME figures/tables.

Instead of the raw across-seed standard deviation, the shaded band and the
table intervals are a 95% bootstrap confidence interval on the MEAN return,
obtained by resampling seeds with replacement (B draws) at each step and taking
the 2.5th / 97.5th percentiles of the bootstrap means. With only 5-7 seeds this
is a more honest summary of uncertainty-on-the-mean than mean +- 1 seed-std.

Reuses the mode palette / ordering from plot_tme_new.py.
Outputs (in out_tme_bootstrap/):
  - results_table_bootstrap.tex / .csv  (mean + 95% CI, train & test)
  - train_return_ci.pdf, test_return_ci.pdf   (mean with 95% CI band)
"""
import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from plot_tme_new import (MODE_META, MODE_ORDER, ACTION_REPEAT,
                          load, load_random, resample, _ewma, _style)

BASE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(BASE, "out_tme_bootstrap")
os.makedirs(OUT, exist_ok=True)

B = 10000          # bootstrap resamples
CI = (2.5, 97.5)   # percentile CI
RNG = np.random.default_rng(0)


def bootstrap_mean_ci(values):
    """values: 1D array over seeds -> (mean, lo, hi) of the bootstrap mean dist."""
    values = np.asarray(values, float)
    values = values[~np.isnan(values)]
    n = len(values)
    if n == 0:
        return np.nan, np.nan, np.nan
    if n == 1:
        return values[0], values[0], values[0]
    idx = RNG.integers(0, n, size=(B, n))
    boot_means = values[idx].mean(axis=1)
    lo, hi = np.percentile(boot_means, CI)
    return values.mean(), lo, hi


def bootstrap_curve_ci(mat):
    """mat: (n_seeds, T) -> mean, lo, hi curves via per-step bootstrap of the mean."""
    n, T = mat.shape
    mean = np.nanmean(mat, axis=0)
    if n == 1:
        return mean, mean.copy(), mean.copy()
    idx = RNG.integers(0, n, size=(B, n))          # (B, n)
    # boot means: (B, T) = mean over resampled seeds at each step
    boot = np.nanmean(mat[idx, :], axis=1)          # (B, T)
    lo = np.nanpercentile(boot, CI[0], axis=0)
    hi = np.nanpercentile(boot, CI[1], axis=0)
    return mean, lo, hi


# ── table: final-performance mean + 95% CI ───────────────────────────────────
def final_values(mode, col, tail):
    out = []
    for _, v in [(s, _ewma(v)) for s, v in load(mode, col)]:
        out.append(v[-tail:].mean())
    return np.array(out)


def final_values_random(col, tail):
    out = []
    for _, v in [(s, _ewma(v)) for s, v in load_random(col)]:
        out.append(v[-tail:].mean())
    return np.array(out)


def make_table():
    rows = []
    for mode in MODE_ORDER:
        m = MODE_META[mode]
        tr = final_values(mode, "train_return", 50)
        te = final_values(mode, "test_return", 20)
        tr_mu, tr_lo, tr_hi = bootstrap_mean_ci(tr)
        te_mu, te_lo, te_hi = bootstrap_mean_ci(te)
        rows.append(dict(id=m["id"], mode=mode, n=len(tr), main=m["main"],
                         train_mu=tr_mu, train_lo=tr_lo, train_hi=tr_hi,
                         test_mu=te_mu, test_lo=te_lo, test_hi=te_hi))
    # random-policy baseline anchor
    tr = final_values_random("train_return", 50)
    te = final_values_random("test_return", 20)
    tr_mu, tr_lo, tr_hi = bootstrap_mean_ci(tr)
    te_mu, te_lo, te_hi = bootstrap_mean_ci(te)
    rows.append(dict(id="RAND", mode="random_baseline", n=len(tr), main=True,
                     train_mu=tr_mu, train_lo=tr_lo, train_hi=tr_hi,
                     test_mu=te_mu, test_lo=te_lo, test_hi=te_hi))
    return pd.DataFrame(rows)


def write_table(df):
    df.to_csv(os.path.join(OUT, "results_table_bootstrap.csv"), index=False)

    def block(sub):
        s = []
        for _, r in sub.iterrows():
            s.append(
                f"    {r['id']} & \\texttt{{{r['mode'].replace('_', chr(92)+'_')}}} & {int(r['n'])} "
                f"& {r['train_mu']:+.1f} & [{r['train_lo']:+.1f}, {r['train_hi']:+.1f}] "
                f"& {r['test_mu']:+.1f} & [{r['test_lo']:+.1f}, {r['test_hi']:+.1f}] \\\\")
        return "\n".join(s)

    main = df[df.main].sort_values("test_mu", ascending=False)
    extra = df[~df.main].sort_values("test_mu", ascending=False)
    tex = f"""% auto-generated by plot_tme_bootstrap.py
% mean with 95% bootstrap CI on the mean (B={B} seed resamples); train=rectangle, test=network-field
\\begin{{tabular}}{{llcccccc}}
  \\toprule
  \\textbf{{ID}} & \\textbf{{Mode}} & \\textbf{{$n$}} &
  \\textbf{{Train$_\\mu$}} & \\textbf{{Train 95\\% CI}} &
  \\textbf{{Test$_\\mu$}}  & \\textbf{{Test 95\\% CI}} \\\\
  \\midrule
{block(main)}
  \\midrule
{block(extra)}
  \\bottomrule
\\end{{tabular}}
"""
    with open(os.path.join(OUT, "results_table_bootstrap.tex"), "w") as f:
        f.write(tex)


# ── curves with bootstrap CI band ────────────────────────────────────────────
def curve_ci(col, ylabel, fname, main_only=True):
    _style()
    fig, ax = plt.subplots(figsize=(7, 4.2))
    grid = np.linspace(0, 100000, 300)
    for mode in MODE_ORDER:
        m = MODE_META[mode]
        if main_only and not m["main"]:
            continue
        mat = resample(load(mode, col), grid)
        if mat.size == 0:
            continue
        mean, lo, hi = bootstrap_curve_ci(mat)
        x = grid * ACTION_REPEAT / 1e5
        ax.plot(x, mean, color=m["color"], ls=m["ls"], lw=m["lw"], zorder=m["z"], label=m["id"])
        ax.fill_between(x, lo, hi, color=m["color"], alpha=0.15, zorder=m["z"], linewidth=0)
    rb = final_values_random(col, 50 if col == "train_return" else 20)
    rb_mu, rb_lo, rb_hi = bootstrap_mean_ci(rb)
    ax.axhline(rb_mu, color="k", lw=1.0, ls=(0, (4, 3)), alpha=0.7, zorder=0,
               label=f"random ({rb_mu:+.0f})")
    ax.axhspan(rb_lo, rb_hi, color="k", alpha=0.06, zorder=0)
    ax.axhline(0, color="k", lw=0.6, alpha=0.4)
    ax.set_xlabel(r"cumulative simulator steps ($\times 10^5$)")
    ax.set_ylabel(ylabel)
    ax.legend(fontsize=8, ncol=2, loc="best")
    fig.savefig(os.path.join(OUT, fname))
    plt.close(fig)
    print("wrote", fname)


if __name__ == "__main__":
    df = make_table()
    show = df[["id", "n", "train_mu", "train_lo", "train_hi",
               "test_mu", "test_lo", "test_hi", "main"]]
    print(show.to_string(index=False))
    write_table(df)
    curve_ci("train_return", "training return (EWMA-50)", "train_return_ci.pdf")
    curve_ci("test_return", "test return, network-field (EWMA-50)", "test_return_ci.pdf")
    print("\nBootstrap outputs in", OUT)
