name: physigym_apple_test_pilot
run-name: ${{ github.actor }}::test physigym on the macosx, all pytest unit tests.

on:
  push:
    branches: ["utest"]  # main
  #pull_request:
  #  branches: ["main"]

env:
  PHYSICELL_CPP: g++-14

jobs:
  build-macosx:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:

    - name: install gcc
      run : |
        if ! brew list gcc@14 &>/dev/null; then
          brew install gcc
        else
          echo "gcc@14 is already installed."
        fi

    - name: check out the physigym repo
      uses: actions/checkout@v4

    - name: install python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: install python3 modules
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest gymnasium "lxml>5.0" matplotlib numpy pandas #pcdl

    - name: install physicell
      run: |
        git clone https://github.com/MathCancer/PhysiCell.git /Users/runner/work/PhysiGym/PhysiCell

    - name: run test tutorial
      run: |
        pytest test/test_physigym_model.py -v
        #pytest test/test_physigym_reload.py -v
