name: physigym_apple_test_pilot
run-name: ${{ github.actor }}::test physigym on macosx, the macosx python3 versions, all unit tests.

on:
  push:
    branches: ["main","patch030_workflow"]
  pull_request:
    branches: ["main","patch030_workflow"]

jobs:
  build-macosx:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:

    - name: install physicell
      run: |
        git clone https://github.com/MathCancer/PhysiCell.git

    - name: check out physigym repo
      uses: actions/checkout@v4

    - name: install python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: install python3 modules
      run: |
        #brew install pipx
        python3 -m pip install --upgrade pip
        python3 -m pip install gymnasium lxml matplotlib numpy pandas pcdl pytest

    - name: run test tutorial
      run: |
        cd test/
        pytest
