name: physigym_apple_test_pilot
run-name: ${{ github.actor }}::test physigym on macosx, the macosx python3 versions, all unit tests.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-macosx:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:

    - name: install physicell
      run: |
        git clone https://github.com/elmbeech/PhysiCell.git
        git switch physigym

    - name: install physigym
      run: |
        git clone https://github.com/Dante-Berth/PhysiGym.git
        
    - name: check out physigym repo
      uses: actions/checkout@v4

    - name: install python3 modules
      run: |
        #brew install pipx
        pip install anndata gymnasium lxml matplotlib numpy pandas pcdl scipy vtk
        which python3
        which python
        which pip3
        which pip

    - name: run test tutorial
      run: |
        cd PhysiGym
        python3 test/all_tutorial.py

