name: physigym_apple_test_pilot
run-name: ${{ github.actor }}::test physigym on the macosx, all pytest unit tests.

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  build-macosx:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:

    - name: install gcc
      run : |
        if ! brew list gcc@13 &>/dev/null; then
          brew install gcc@13
        else
          echo "gcc@13 is already installed."
        fi

    - name: check out the physigym repo
      uses: actions/checkout@v4

    - name: install python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: install python3 modules
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest gymnasium lxml matplotlib numpy pandas #pcdl

    - name: install physicell
      run: |
        git clone https://github.com/MathCancer/PhysiCell.git /Users/runner/work/PhysiGym/PhysiCell

    - name: run test tutorial
      run: |
        pytest test/test_physigym_model.py -v
