name: physigym_linux_test_pilot
run-name: ${{ github.actor }}::test physigym on the linux os, all pytest unit tests.

on:
  push:
    branches: ["main", "patch030_workflow"]
  pull_request:
    branches: ["main", "patch030_workflow"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

    - name: check out the physigym repo
      uses: actions/checkout@v4

    - name: install python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: install python modules
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest gymnasium lxml matplotlib numpy pandas pcdl
        which python3
        which python
        which pip3
        which pip

    - name: install physicell
      run: |
        git clone https://github.com/MathCancer/PhysiCell.git /home/runner/work/PhysiGym/PhysiCell

    - name: run the pytest
      run: |
        pytest test/test_physigym_model.py -v
        pytest test/test_physigym_reload.py -v
